version: '3.8'

services:
  mariadb:
    image: mariadb:sdemnati
    restart: always
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my-net
    env_file:
      - .env
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:sdemnati
    restart: always
    build: ./requirements/wordpress
    networks:
      - my-net
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
  nginx:
    image: nginx:sdemnati
    restart: always
    build: ./requirements/nginx
    networks:
      - my-net
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /Users/sdemnati/data/mariadb
      type: none
      o: bind

  wordpress:
    driver: local
    driver_opts:
      device: /Users/sdemnati/data/wordpress
      type: none
      o: bind

networks:
  my-net: