version: "3.8"

services:
  # Database Service
  mariadb:
    image: mariadb:sdemnati
    container_name: mariadb
    restart: always
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my-net
    env_file:
      - .env
    ports:
      - 3306:3306
    # secrets:
    #   - db_password
  # WordPress Service
  wordpress:
    container_name: wordpress
    image: wordpress:sdemnati
    restart: always
    build: ./wordpress
    networks:
      - my-net
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - 9000:9000
    # secrets:
    #   - db_password
  # Nginx Service
  nginx:
    container_name: nginx
    image: nginx:sdemnati
    restart: always
    build: ./nginx
    networks:
      - my-net
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
  # Redis Service
  redis:
    container_name: redis
    image: redis:sdemnati
    restart: always
    build: ./bonus/redis
    networks:
      - my-net
    ports:
      - 6379:6379
  # Static Website Service
  static-website:
    container_name: static-website
    image: static-website:sdemnati
    restart: always
    build: ./bonus/static-website
    networks:
      - my-net
    ports:
      - "8080:8080"
  # Adminer Service
  adminer:
    container_name: adminer
    image: adminer:sdemnati
    restart: always
    build: ./bonus/adminer
    networks:
      - my-net
    ports:
      - 8000:8000
  # Portainer Service
  portainer:
    image: portainer:sdemnati
    container_name: portainer
    restart: always
    build: ./bonus/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9000
  # FTP Server Service
  ftp:
    image: ftp:sdemnati
    build: ./bonus/ftp
    container_name: ftp
    ports:
      - "50000-50001:50000-50001"
      - "21:21"
      # - "20:20"
    volumes:
      - wordpress:/home/$FTP_USER/ftp
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - my-net
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/sdemnati/data/mariadb
      type: none
      o: bind

  wordpress:
    driver: local
    driver_opts:
      device: /home/sdemnati/data/wordpress
      type: none
      o: bind

# secrets:
#   db_password:
    # file: ./secrets/db_password.txt

networks:
  my-net:
    driver: bridge