version: '3.8'

services:
  mariadb:
    image: mariadb:sdemnati
    restart: always
    build: ./mariadb
    networks:
      - my-net

  wordpress:
    image: mariadb:sdemnati
    restart: always
    build: ./wordpress
    networks:
      - my-net
    depends_on:
      - mariadb
  nginx:
    image: nginx:sdemnati
    restart: always
    build: ./nginx
    networks:
      - my-net
    

networks:
  my-net: